<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <!-- Parent project details -->
    <parent>
        <artifactId>realm-framework</artifactId>
        <groupId>cn.realm.cloud</groupId>
        <version>${revision}</version>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>realm-spring-boot-starter-rpc</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>
        OpenFeign: Provides RESTful API calls
    </description>
    <url>https://github.com/</url>

    <dependencies>
        <!-- Common dependencies -->
        <dependency>
            <groupId>cn.realm.cloud</groupId>
            <artifactId>realm-common</artifactId> <!-- 项目通用工具和基础类 -->
        </dependency>

        <!-- RPC remote call dependencies -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-okhttp</artifactId>
        </dependency>

        <!-- Utility dependencies -->
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
    </dependencies>
</project>
