<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <!-- 基础项目定义 -->
    <parent>
        <groupId>cn.realm.cloud</groupId>
        <artifactId>realm-framework</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>realm-spring-boot-starter-job</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>分布式任务调度拓展，基于 XXL-Job 实现</description>
    <url>https://github.com/</url>

    <dependencies>
        <!-- ==================== 基础依赖 ==================== -->
        <dependency>
            <groupId>cn.realm.cloud</groupId>
            <artifactId>realm-framework-common</artifactId>
        </dependency>

        <!-- ==================== Spring Boot 支持 ==================== -->
        <!-- 配置元数据生成 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional> <!-- 生成配置提示文件 -->
        </dependency>
        <!-- 核心启动器 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <optional>true</optional> <!-- 仅本 starter 使用，不传递依赖 -->
        </dependency>

        <!-- ==================== XXL-Job 任务调度 ==================== -->
        <dependency>
            <groupId>com.xuxueli</groupId>
            <artifactId>xxl-job-core</artifactId> <!-- 分布式任务调度核心库 -->
        </dependency>

        <!-- ==================== 校验相关 ==================== -->
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId> <!-- 参数校验规范 -->
        </dependency>
    </dependencies>

</project>
