#nacos:
#  discovery:
#    server-addr: ${nacos.server.address}
#    namespace: ${nacos.server.namespace}
#    group: ${nacos.server.group}
#  config:
#    server-addr: ${nacos.server.address}
#    namespace: ${nacos.server.namespace}
#    data-id: ${nacos.server.dataId}
#    username: ${nacos.server.username}
#    password: ${nacos.server.password}
#    type: yaml
#    auto-refresh: true
